# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoLabel(object):
    def setupUi(self, autoLabel):
        autoLabel.setObjectName("autoLabel")
        autoLabel.resize(1130, 890)
        self.gridLayout = QtWidgets.QGridLayout(autoLabel)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOpenDir = QtWidgets.QPushButton(autoLabel)
        self.pushButtonOpenDir.setObjectName("pushButtonOpenDir")
        self.horizontalLayout.addWidget(self.pushButtonOpenDir)
        self.pushButtonPrevImage = QtWidgets.QPushButton(autoLabel)
        self.pushButtonPrevImage.setObjectName("pushButtonPrevImage")
        self.horizontalLayout.addWidget(self.pushButtonPrevImage)
        self.pushButtonNextImage = QtWidgets.QPushButton(autoLabel)
        self.pushButtonNextImage.setObjectName("pushButtonNextImage")
        self.horizontalLayout.addWidget(self.pushButtonNextImage)
        self.pushButtonCreateRectBox = QtWidgets.QPushButton(autoLabel)
        self.pushButtonCreateRectBox.setObjectName("pushButtonCreateRectBox")
        self.horizontalLayout.addWidget(self.pushButtonCreateRectBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileListWidget = QtWidgets.QListWidget(autoLabel)
        self.fileListWidget.setMaximumSize(QtCore.QSize(256, 16777215))
        self.fileListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.fileListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileListWidget.setObjectName("fileListWidget")
        self.horizontalLayout_2.addWidget(self.fileListWidget)
        self.graphicsView = ZoomableGraphicsView(autoLabel)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.categoryListWidget = QtWidgets.QListWidget(autoLabel)
        self.categoryListWidget.setMaximumSize(QtCore.QSize(256, 16777215))
        self.categoryListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.categoryListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.categoryListWidget.setObjectName("categoryListWidget")
        self.horizontalLayout_2.addWidget(self.categoryListWidget)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.thumbnailPreview = QtWidgets.QListWidget(autoLabel)
        self.thumbnailPreview.setMaximumSize(QtCore.QSize(16777215, 150))
        self.thumbnailPreview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thumbnailPreview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.thumbnailPreview.setIconSize(QtCore.QSize(100, 100))
        self.thumbnailPreview.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.thumbnailPreview.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.thumbnailPreview.setMovement(QtWidgets.QListView.Static)
        self.thumbnailPreview.setProperty("isWrapping", False)
        self.thumbnailPreview.setViewMode(QtWidgets.QListView.IconMode)
        self.thumbnailPreview.setObjectName("thumbnailPreview")
        self.gridLayout.addWidget(self.thumbnailPreview, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(autoLabel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)

        self.retranslateUi(autoLabel)
        QtCore.QMetaObject.connectSlotsByName(autoLabel)

    def retranslateUi(self, autoLabel):
        _translate = QtCore.QCoreApplication.translate
        autoLabel.setWindowTitle(_translate("autoLabel", "AutoLabelPlus"))
        self.pushButtonOpenDir.setText(_translate("autoLabel", "Open Dir"))
        self.pushButtonOpenDir.setShortcut(_translate("autoLabel", "Ctrl+O"))
        self.pushButtonPrevImage.setText(_translate("autoLabel", "Prev Image"))
        self.pushButtonPrevImage.setShortcut(_translate("autoLabel", "A"))
        self.pushButtonNextImage.setText(_translate("autoLabel", "Next Image"))
        self.pushButtonNextImage.setShortcut(_translate("autoLabel", "D"))
        self.pushButtonCreateRectBox.setText(_translate("autoLabel", "Create RectBox"))
        self.pushButtonCreateRectBox.setShortcut(_translate("autoLabel", "W"))
        self.fileListWidget.setSortingEnabled(True)
        self.categoryListWidget.setSortingEnabled(True)
        self.label.setText(_translate("autoLabel", "X = 0, Y = 0"))
from zoomable_graphics_view import ZoomableGraphicsView
